USE [master]
GO

/****** Object:  Database [rentcar]    Script Date: 04/02/2021 23:40:36 ******/
CREATE DATABASE [rentcar]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ewave', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQL12\MSSQL\DATA\ewave.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ewave_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQL12\MSSQL\DATA\ewave_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [rentcar] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [rentcar].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [rentcar] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [rentcar] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [rentcar] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [rentcar] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [rentcar] SET ARITHABORT OFF 
GO

ALTER DATABASE [rentcar] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [rentcar] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [rentcar] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [rentcar] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [rentcar] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [rentcar] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [rentcar] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [rentcar] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [rentcar] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [rentcar] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [rentcar] SET  DISABLE_BROKER 
GO

ALTER DATABASE [rentcar] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [rentcar] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [rentcar] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [rentcar] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [rentcar] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [rentcar] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [rentcar] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [rentcar] SET RECOVERY FULL 
GO

ALTER DATABASE [rentcar] SET  MULTI_USER 
GO

ALTER DATABASE [rentcar] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [rentcar] SET DB_CHAINING OFF 
GO

ALTER DATABASE [rentcar] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [rentcar] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [rentcar] SET  READ_WRITE 
GO


